#!/bin/bash

LIB_SOURCE=${LIB_SOURCE:?"Need to set LIB_SOURCE non-empty"}
DESTINATION=${DESTINATION:="/Volumes/CIRCUITPY"}

libs=(
  adafruit_74hc595.mpy
  adafruit_bus_device
  adafruit_character_lcd
  adafruit_datetime.mpy
  adafruit_esp32spi
  adafruit_mcp230xx
  adafruit_requests.mpy
  adafruit_veml7700.mpy
  adafruit_register
)

echo "Copying code.py to $DESTINATION/code.py"
cp -rX "$PWD/code.py" "$DESTINATION/code.py"

SECRETS_PY_FILE=${SECRETS_PY_FILE:=$PWD/secrets.py}
echo "Copying secrets.py from $SECRETS_PY_FILE to $DESTINATION/secrets.py"
cp -rX "$SECRETS_PY_FILE" "$DESTINATION/secrets.py"

echo "Copying libs to $DESTINATION/lib/ ... "
for lib in "${libs[@]}"
do
  echo "- copying $lib"
  cp -rX "$LIB_SOURCE/$lib" "$DESTINATION/lib/"
done
echo "Copying libs... done"


